apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secret-dburl
  namespace: tenant-planka
spec:
  data:
  - remoteRef:
      key: tenant-planka-cluster-db-username
      metadataPolicy: None
      conversionStrategy: Default
      decodingStrategy: None
    secretKey: username
  - remoteRef:
      key: tenant-planka-cluster-db-password
      metadataPolicy: None
      conversionStrategy: Default
      decodingStrategy: None
    secretKey: password
  - remoteRef:
      key: tenant-planka-cluster-db-dbname
      metadataPolicy: None
      conversionStrategy: Default
      decodingStrategy: None
    secretKey: dbname
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-cluster-secret-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    name: secret-dburl
    template:
      data:
        uri: postgresql://{{ .username }}:{{ .password }}@cluster-rw.tenant-planka.svc.cluster.local:5432/{{ .dbname }}
      engineVersion: v2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secret
  namespace: tenant-planka
spec:
  data:
  - remoteRef:
      key: tenant-planka-cluster-db-password
      metadataPolicy: None
      conversionStrategy: Default
      decodingStrategy: None
    secretKey: key
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-cluster-secret-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    name: secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secret-admin
  namespace: tenant-planka
spec:
  data:
  - remoteRef:
      key: tenant-planka-cluster-db-password
      metadataPolicy: None
      conversionStrategy: Default
      decodingStrategy: None
    secretKey: password
  - remoteRef:
      key: tenant-planka-cluster-db-username
      metadataPolicy: None
      conversionStrategy: Default
      decodingStrategy: None
    secretKey: username
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-cluster-secret-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    name: secret-admin
