apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secret-dburl
  namespace: tenant-planka
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-tenant-planka
    kind: SecretStore
  target:
    name: secret-dburl
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@cluster-rw.tenant-planka.svc.cluster.local:5432/{{ .dbname }}"
  data:
    - secretKey: username
      remoteRef:
        key: tenant-planka-cluster-app-username
    - secretKey: password
      remoteRef:
        key: tenant-planka-cluster-app-password
    - secretKey: dbname
      remoteRef:
        key: tenant-planka-cluster-app-dbname
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secret
  namespace: tenant-planka
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-tenant-planka
    kind: SecretStore
  target:
    name: secret
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: tenant-planka-app-secret-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secret-admin
  namespace: tenant-planka
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-tenant-planka
    kind: SecretStore
  target:
    name: secret-admin
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_EMAIL
      remoteRef:
        key: tenant-planka-admin-email
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: tenant-planka-admin-password
    - secretKey: ADMIN_USERNAME
      remoteRef:
        key: tenant-planka-admin-username
    - secretKey: ADMIN_NAME
      remoteRef:
        key: tenant-planka-admin-name
