apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-workload-identity
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  serviceAccountTemplate:
    metadata:
      name: crossplane-gcp
      annotations:
        iam.gke.io/gcp-service-account: "inenp-crossplane-sa@sacred-garden-501011-e0.iam.gserviceaccount.com"
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-kubernetes-runtime
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  serviceAccountTemplate:
    metadata:
      name: provider-kubernetes  # stable name
