domainFilters:
  - plateng.fhbgl.study

policy: sync
txtOwnerId: external-dns-${SITE}-google
txtPrefix: externaldns-
provider:
  name: google

sources:
  - crd
  - service
  - gateway-httproute

enableGatewayListenerSets: true

annotationFilter: "external-dns.alpha.kubernetes.io/provider=public"

deploymentAnnotations:
  reloader.stakater.com/auto: "true"

extraArgs:
  google-project: sacred-garden-501011-e0
  google-batch-change-size: 1000

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 256Mi

serviceAccount:
  create: true
  name: external-dns
  annotations:
    iam.gke.io/gcp-service-account: inenp-external-dns-sa@sacred-garden-501011-e0.iam.gserviceaccount.com
