apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-cluster-app
  namespace: tenant-planka
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 1h
  secretStoreRefs:
    - name: gcpsm-tenant-planka
      kind: SecretStore
  selector:
    secret:
      name: cluster-app
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: tenant-planka-cluster-app-username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: tenant-planka-cluster-app-password
    - match:
        secretKey: dbname
        remoteRef:
          remoteKey: tenant-planka-cluster-app-dbname
