apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-cluster-app
  namespace: tenant-planka
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 1h
  secretStoreRefs:
    - name: gcpsm-cluster-secret-store
      kind: ClusterSecretStore
  selector:
    secret:
      name: cluster-app
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: tenant-planka-cluster-db-username
      conversionStrategy: None
    - match:
        secretKey: password
        remoteRef:
          remoteKey: tenant-planka-cluster-db-password
      conversionStrategy: None
    - match:
        secretKey: dbname
        remoteRef:
          remoteKey: tenant-planka-cluster-db-dbname
      conversionStrategy: None
    - match:
        secretKey: uri
        remoteRef:
          remoteKey: tenant-planka-cluster-db-uri
      conversionStrategy: None
