apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcpsm-tenant-planka
  namespace: tenant-planka
spec:
  provider:
    gcpsm:
      projectID: 
      auth:
        workloadIdentity:
          clusterName: my-gke-cluster
          serviceAccountRef:
            name: external-secrets
