---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: gateway-crds-helm
    repo: oci://docker.io/envoyproxy
    releaseName: gateway-crds-helm
    version: 1.8.1
    valuesFile: values.yaml
    namespace: gateway-system
