provider:
  packages: []

resourcesCrossplane:
  limits:
    cpu: null
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi

resourcesRBACManager:
  limits:
    cpu: null
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 512Mi

serviceAccount:
  create: true
  name: crossplane
  customAnnotations:
    iam.gke.io/gcp-service-account: "inenp-crossplane-sa@sacred-garden-501011-e0.iam.gserviceaccount.com"
