apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcpsm-cluster-secret-store
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      projectID: sacred-garden-501011-e0
      auth:
        workloadIdentity:
          clusterName: gitops-cluster-cnua22
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
