apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - name: gateway-api-crds
            path: infra/envoy-gateway/crds
            namespace: gateway-system
            syncWave: "-10"
          - name: gateway-api
            path: infra/envoy-gateway
            namespace: gateway-system
            syncWave: "0"
          - name: cert-manager
            path: infra/cert-manager
            namespace: cert-manager
            syncWave: "-1"
          - name: external-dns
            path: infra/external-dns
            namespace: external-dns
            syncWave: "0"
          - name: external-secrets
            path: infra/external-secrets
            namespace: external-secrets
            syncWave: "0"
          - name: crossplane
            path: infra/crossplane
            namespace: crossplane-system
            syncWave: "-1"
          - name: crossplane-configs
            path: infra/crossplane/configs
            namespace: crossplane-system
            syncWave: "0"
  template:
    metadata:
      name: "{{ .name }}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: "{{ .syncWave }}"
    spec:
      project: infra
      sources:
        - repoURL: https://github.com/lukas1102/platform-2at-gitops-gke.git
          targetRevision: HEAD
          path: "{{ .path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
